GET http://localhost:28017/Players/

###

GET http://localhost:28017/Players/63f6a040a04e2f0dbbc9fa9e

###

GET http://localhost:28017/Players/name/Amara

###

POST http://localhost:28017/Players
Content-Type: application/json

{
    "full_name": "Amara",
    "age": 10,
    "position": "Midfielder",
    "current_club": "Liverpool FC",
    "nationality": "Ivory Coast"
}

### 

DELETE http://localhost:28017/Players/remove/Amara

###

PATCH http://localhost:28017/Players/63f6a040a04e2f0dbbc9fa9e
Content-Type: application/json

{
    "full_name": "Green Blue"
}
